// -------------------------------------------------------------
// 
// File Name: D:\slsf_randgen\slsf\reportsneo\2024-03-07-15-43-51\Verilog_hdlsrc\sampleModel12940_sub\cfblk262.v
// Created: 2024-03-08 13:13:54
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: cfblk262
// Source Path: sampleModel12940_sub/Subsystem/cfblk262
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module cfblk262
          (clk,
           reset,
           enb,
           y);


  input   clk;
  input   reset;
  input   enb;
  output  [7:0] y;  // uint8


  reg [7:0] Output_out1;  // uint8
  wire [7:0] Increment_Real_World_out1;  // uint8
  wire [7:0] Wrap_To_Zero_out1;  // uint8


  Increment_Real_World_block2 u_Increment_Real_World (.u(Output_out1),  // uint8
                                                      .y(Increment_Real_World_out1)  // uint8
                                                      );

  Wrap_To_Zero_block2 u_Wrap_To_Zero (.U(Increment_Real_World_out1),  // uint8
                                      .Y(Wrap_To_Zero_out1)  // uint8
                                      );

  always @(posedge clk or posedge reset)
    begin : Output_rsvd_process
      if (reset == 1'b1) begin
        Output_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Output_out1 <= Wrap_To_Zero_out1;
        end
      end
    end



  assign y = Output_out1;

endmodule  // cfblk262

