// -------------------------------------------------------------
// 
// File Name: D:\slsf_randgen\slsf\reportsneo\2024-03-07-15-43-51\Verilog_hdlsrc\sampleModel12940_sub\Wrap_To_Zero.v
// Created: 2024-03-08 13:13:54
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Wrap_To_Zero
// Source Path: sampleModel12940_sub/Subsystem/cfblk258/Wrap To Zero
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Wrap_To_Zero
          (U,
           Y);


  input   [7:0] U;  // uint8
  output  [7:0] Y;  // uint8


  wire switch_compare_1;
  wire [7:0] Constant_out1;  // uint8
  wire [7:0] FixPt_Switch_out1;  // uint8

  // U(k)


  assign switch_compare_1 = U > 8'b00000111;



  assign Constant_out1 = 8'b00000000;



  assign FixPt_Switch_out1 = (switch_compare_1 == 1'b0 ? U :
              Constant_out1);



  assign Y = FixPt_Switch_out1;

endmodule  // Wrap_To_Zero

