/* Generated by Yosys 0.37+1 (git sha1 e1f4c5c9cbb, clang  -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:14.1-54.10" *)
module module55(y, clk, wire56, wire57, wire58, wire59);
  wire [13:0] _000_;
  wire [6:0] _001_;
  wire [2:0] _002_;
  wire [1:0] _003_;
  wire [9:0] _004_;
  wire [4:0] _005_;
  wire [2:0] _006_;
  wire _007_;
  wire [8:0] _008_;
  wire [3:0] _009_;
  wire [1:0] _010_;
  wire _011_;
  wire [3:0] _012_;
  wire [1:0] _013_;
  wire [9:0] _014_;
  wire [4:0] _015_;
  wire [1:0] _016_;
  wire _017_;
  wire [3:0] _018_;
  wire [1:0] _019_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.21-46.48" *)
  (* unused_bits = "2 3 4 5 6 7 8 9 10 11 12 13 14" *)
  wire [14:0] _020_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)
  wire _021_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)
  wire _022_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.24-45.65" *)
  wire _023_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *)
  wire _024_;
  (* force_downto = 32'd1 *)
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.29-41.71|/usr/local/bin/../share/yosys/techmap.v:266.22-266.23" *)
  wire _025_;
  (* force_downto = 32'd1 *)
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.29-41.71|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _026_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)
  wire [17:0] _027_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)
  wire [7:0] _028_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *)
  wire [19:0] _029_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:16.30-16.33" *)
  input clk;
  wire clk;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:27.23-27.28" *)
  reg [7:0] reg77 = 8'h00;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:26.24-26.29" *)
  wire [17:0] reg78;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:25.30-25.35" *)
  reg [4:0] reg79 = 5'h00;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:24.24-24.29" *)
  wire [19:0] reg80;
  (* init = 18'bx0xxxxxxxxxxxxxxxx *)
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:23.24-23.29" *)
  wire [17:0] reg81;
  (* init = 10'b000000000x *)
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:22.30-22.35" *)
  wire [9:0] reg82;
  (* init = 13'bxxxxxxxxxxxx0 *)
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:21.23-21.28" *)
  wire [12:0] reg83;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:17.30-17.36" *)
  input [6:0] wire56;
  wire [6:0] wire56;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:18.38-18.44" *)
  input [20:0] wire57;
  wire [20:0] wire57;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:19.31-19.37" *)
  input [17:0] wire58;
  wire [17:0] wire58;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:20.30-20.36" *)
  input [13:0] wire59;
  wire [13:0] wire59;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:15.35-15.36" *)
  output [372:0] y;
  wire [372:0] y;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    reg79[3] <= reg77[4];
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    reg79[4] <= reg77[5];
  reg \reg82_reg[1]  = 1'h0;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    \reg82_reg[1]  <= _020_[1];
  assign reg82[1] = \reg82_reg[1] ;
  reg \reg81_reg[16]  = 1'h0;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    \reg81_reg[16]  <= _025_;
  assign reg81[16] = \reg81_reg[16] ;
  reg \reg83_reg[0]  = 1'h0;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    \reg83_reg[0]  <= 1'h1;
  assign reg83[0] = \reg83_reg[0] ;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    reg77[0] <= wire58[0];
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    reg77[1] <= wire58[1];
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    reg77[2] <= wire58[2];
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    reg77[3] <= wire58[3];
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    reg77[4] <= wire58[4];
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    reg77[5] <= wire58[5];
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    reg77[6] <= wire58[6];
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    reg77[7] <= wire58[7];
  reg \reg82_reg[9]  = 1'h0;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    if (_023_) \reg82_reg[9]  <= 1'h0;
    else \reg82_reg[9]  <= wire59[8];
  assign reg82[9] = \reg82_reg[9] ;
  reg \reg82_reg[2]  = 1'h0;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    if (_023_) \reg82_reg[2]  <= 1'h0;
    else \reg82_reg[2]  <= wire59[1];
  assign reg82[2] = \reg82_reg[2] ;
  reg \reg82_reg[3]  = 1'h0;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    if (_023_) \reg82_reg[3]  <= 1'h0;
    else \reg82_reg[3]  <= wire59[2];
  assign reg82[3] = \reg82_reg[3] ;
  reg \reg82_reg[4]  = 1'h0;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    if (_023_) \reg82_reg[4]  <= 1'h0;
    else \reg82_reg[4]  <= wire59[3];
  assign reg82[4] = \reg82_reg[4] ;
  reg \reg82_reg[5]  = 1'h0;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    if (_023_) \reg82_reg[5]  <= 1'h0;
    else \reg82_reg[5]  <= wire59[4];
  assign reg82[5] = \reg82_reg[5] ;
  reg \reg82_reg[6]  = 1'h0;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    if (_023_) \reg82_reg[6]  <= 1'h0;
    else \reg82_reg[6]  <= wire59[5];
  assign reg82[6] = \reg82_reg[6] ;
  reg \reg82_reg[7]  = 1'h0;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    if (_023_) \reg82_reg[7]  <= 1'h0;
    else \reg82_reg[7]  <= wire59[6];
  assign reg82[7] = \reg82_reg[7] ;
  reg \reg82_reg[8]  = 1'h0;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    if (_023_) \reg82_reg[8]  <= 1'h0;
    else \reg82_reg[8]  <= wire59[7];
  assign reg82[8] = \reg82_reg[8] ;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    reg79[0] <= reg77[1];
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    reg79[1] <= reg77[2];
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:29.3-53.8" *)
  always @(posedge clk)
    reg79[2] <= reg77[3];
  assign _025_ = ~_026_;
  assign _001_[0] = _000_[0] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.39-41.70" *)  _000_[1];
  assign _001_[1] = _000_[2] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.39-41.70" *)  _000_[3];
  assign _001_[2] = _000_[4] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.39-41.70" *)  _000_[5];
  assign _001_[3] = _000_[6] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.39-41.70" *)  _000_[7];
  assign _001_[4] = _000_[8] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.39-41.70" *)  _000_[9];
  assign _001_[5] = _000_[10] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.39-41.70" *)  _000_[11];
  assign _001_[6] = _000_[12] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.39-41.70" *)  _000_[13];
  assign _002_[0] = _001_[0] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.39-41.70" *)  _001_[1];
  assign _002_[1] = _001_[2] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.39-41.70" *)  _001_[3];
  assign _002_[2] = _001_[4] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.39-41.70" *)  _001_[5];
  assign _003_[0] = _002_[0] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.39-41.70" *)  _002_[1];
  assign _003_[1] = _002_[2] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.39-41.70" *)  _001_[6];
  assign _026_ = _003_[0] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:41.39-41.70" *)  _003_[1];
  assign _004_[0] = wire57[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  wire57[1];
  assign _004_[1] = wire57[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  wire57[3];
  assign _004_[2] = wire57[4] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  wire57[5];
  assign _004_[3] = wire57[6] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  wire57[7];
  assign _004_[4] = wire57[8] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  wire57[9];
  assign _004_[5] = wire57[10] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  wire57[11];
  assign _004_[6] = wire57[12] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  wire57[13];
  assign _004_[7] = wire57[14] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  wire57[15];
  assign _004_[8] = wire57[16] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  wire57[17];
  assign _004_[9] = wire57[18] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  wire57[19];
  assign _005_[0] = _004_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  _004_[1];
  assign _005_[1] = _004_[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  _004_[3];
  assign _005_[2] = _004_[4] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  _004_[5];
  assign _005_[3] = _004_[6] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  _004_[7];
  assign _005_[4] = _004_[8] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  _004_[9];
  assign _006_[0] = _005_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  _005_[1];
  assign _006_[1] = _005_[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  _005_[3];
  assign _006_[2] = _005_[4] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  wire57[20];
  assign _007_ = _006_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  _006_[1];
  assign _021_ = _007_ |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *)  _006_[2];
  assign _008_[0] = _027_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _027_[1];
  assign _008_[1] = _027_[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _027_[3];
  assign _008_[2] = _027_[4] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _027_[5];
  assign _008_[3] = _027_[6] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _027_[7];
  assign _008_[4] = _027_[8] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _027_[9];
  assign _008_[5] = _027_[10] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _027_[11];
  assign _008_[6] = _027_[12] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _027_[13];
  assign _008_[7] = _027_[14] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _027_[15];
  assign _008_[8] = _027_[16] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _027_[17];
  assign _009_[0] = _008_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _008_[1];
  assign _009_[1] = _008_[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _008_[3];
  assign _009_[2] = _008_[4] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _008_[5];
  assign _009_[3] = _008_[6] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _008_[7];
  assign _010_[0] = _009_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _009_[1];
  assign _010_[1] = _009_[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _009_[3];
  assign _011_ = _010_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _010_[1];
  assign _022_ = _011_ |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *)  _008_[8];
  assign _012_[0] = reg77[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *)  reg77[1];
  assign _012_[1] = reg77[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *)  reg77[3];
  assign _012_[2] = reg77[4] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *)  reg77[5];
  assign _012_[3] = reg77[6] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *)  reg77[7];
  assign _013_[0] = _012_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *)  _012_[1];
  assign _013_[1] = _012_[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *)  _012_[3];
  assign _024_ = _013_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *)  _013_[1];
  assign _014_[0] = _029_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.20-45.55" *)  _029_[1];
  assign _014_[1] = _029_[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.20-45.55" *)  _029_[3];
  assign _014_[2] = _029_[4] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.20-45.55" *)  _029_[5];
  assign _014_[3] = _029_[6] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.20-45.55" *)  _029_[7];
  assign _014_[4] = _029_[8] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.20-45.55" *)  _029_[9];
  assign _014_[5] = _029_[10] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.20-45.55" *)  _029_[11];
  assign _014_[6] = _029_[12] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.20-45.55" *)  _029_[13];
  assign _015_[0] = _014_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.20-45.55" *)  _014_[1];
  assign _015_[1] = _014_[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.20-45.55" *)  _014_[3];
  assign _015_[2] = _014_[4] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.20-45.55" *)  _014_[5];
  assign _016_[0] = _015_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.20-45.55" *)  _015_[1];
  assign _016_[1] = _015_[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.20-45.55" *)  _014_[6];
  assign _017_ = _016_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.20-45.55" *)  _016_[1];
  assign _018_[0] = _028_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.24-45.65" *)  _028_[1];
  assign _018_[1] = _028_[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.24-45.65" *)  _028_[3];
  assign _018_[2] = _028_[4] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.24-45.65" *)  _028_[5];
  assign _018_[3] = _028_[6] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.24-45.65" *)  _022_;
  assign _019_[0] = _018_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.24-45.65" *)  _018_[1];
  assign _019_[1] = _018_[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.24-45.65" *)  _018_[3];
  assign _023_ = _019_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.24-45.65" *)  _019_[1];
  assign _027_[0] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) reg77[0] : wire58[0];
  assign _027_[1] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) reg77[1] : wire58[1];
  assign _027_[2] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) reg77[2] : wire58[2];
  assign _027_[3] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) reg77[3] : wire58[3];
  assign _027_[4] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) reg77[4] : wire58[4];
  assign _027_[5] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) reg77[5] : wire58[5];
  assign _027_[6] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) reg77[6] : wire58[6];
  assign _027_[7] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) reg77[7] : wire58[7];
  assign _027_[8] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) 1'h0 : wire58[8];
  assign _027_[9] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) 1'h0 : wire58[9];
  assign _027_[10] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) 1'h0 : wire58[10];
  assign _027_[11] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) 1'h0 : wire58[11];
  assign _027_[12] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) 1'h0 : wire58[12];
  assign _027_[13] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) 1'h0 : wire58[13];
  assign _027_[14] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) 1'h0 : wire58[14];
  assign _027_[15] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) 1'h0 : wire58[15];
  assign _027_[16] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) 1'h0 : wire58[16];
  assign _027_[17] = _021_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.26-42.49" *) 1'h0 : wire58[17];
  assign _028_[0] = _022_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *) 1'h1 : wire59[2];
  assign _028_[1] = _022_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *) 1'h1 : wire59[3];
  assign _028_[2] = _022_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *) 1'h0 : wire59[4];
  assign _028_[3] = _022_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *) 1'h0 : wire59[5];
  assign _028_[4] = _022_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *) 1'h1 : wire59[6];
  assign _028_[5] = _022_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *) 1'h1 : wire59[7];
  assign _028_[6] = _022_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.25-43.54" *) 1'h0 : wire59[8];
  assign _029_[0] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[0];
  assign _029_[1] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[1];
  assign _029_[2] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[2];
  assign _029_[3] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[3];
  assign _029_[4] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[4];
  assign _029_[5] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[5];
  assign _029_[6] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[6];
  assign _029_[7] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[7];
  assign _029_[8] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[8];
  assign _029_[9] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[9];
  assign _029_[10] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[10];
  assign _029_[11] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[11];
  assign _029_[12] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[12];
  assign _029_[13] = _024_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:44.21-44.43" *) 1'h0 : wire59[13];
  assign _020_[1] = _023_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:42.24-45.65" *) _017_ : wire59[0];
  assign _000_[0] = ~(* src = {0{1'b0}} *) wire59[0];
  assign _000_[1] = ~(* src = {0{1'b0}} *) wire59[1];
  assign _000_[2] = ~(* src = {0{1'b0}} *) wire59[2];
  assign _000_[3] = ~(* src = {0{1'b0}} *) wire59[3];
  assign _000_[4] = ~(* src = {0{1'b0}} *) wire59[4];
  assign _000_[5] = ~(* src = {0{1'b0}} *) wire59[5];
  assign _000_[6] = ~(* src = {0{1'b0}} *) wire59[6];
  assign _000_[7] = ~(* src = {0{1'b0}} *) wire59[7];
  assign _000_[8] = ~(* src = {0{1'b0}} *) wire59[8];
  assign _000_[9] = ~(* src = {0{1'b0}} *) wire59[9];
  assign _000_[10] = ~(* src = {0{1'b0}} *) wire59[10];
  assign _000_[11] = ~(* src = {0{1'b0}} *) wire59[11];
  assign _000_[12] = ~(* src = {0{1'b0}} *) wire59[12];
  assign _000_[13] = ~(* src = {0{1'b0}} *) wire59[13];
  assign _014_[9:7] = 3'h0;
  assign _015_[4:3] = { 1'h0, _014_[6] };
  assign _020_[0] = 1'h0;
  assign _028_[7] = _022_;
  assign _029_[19:14] = 6'h00;
  assign reg78 = { 16'h0000, reg77[5], 1'h0 };
  assign reg80 = 20'h00000;
  assign { reg81[17], reg81[15:0] } = { reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16] };
  assign reg82[0] = 1'h0;
  assign reg83[12:1] = 12'h000;
  assign y = { 293'h00000000000000000000000000000000000000000000000000000000000000000000000000, reg83[0], reg82[9:1], 1'h0, reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], reg81[16], 20'h00000, reg79, 16'h0000, reg77[5], 1'h0, reg77 };
endmodule

(* cells_not_processed =  1  *)
(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:1.1-12.10" *)
module top(y, wire4, wire2, wire1, wire0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire [10:0] _005_;
  wire [4:0] _006_;
  wire [2:0] _007_;
  wire _008_;
  wire [10:0] _009_;
  wire [4:0] _010_;
  wire [2:0] _011_;
  wire _012_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62" *)
  wire [21:0] _013_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)
  wire _014_;
  (* force_downto = 32'd1 *)
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [21:0] _015_;
  (* force_downto = 32'd1 *)
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6 8 9 10 11 12 13 14 16 17 18 20" *)
  wire [21:0] _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _020_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _021_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _022_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _023_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _024_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)
  (* unused_bits = "6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21" *)
  wire [22:0] _025_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.46-11.72" *)
  (* unused_bits = "6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21" *)
  wire [21:0] _026_;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:6.38-6.43" *)
  input [21:0] wire0;
  wire [21:0] wire0;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:5.31-5.36" *)
  input [21:0] wire1;
  wire [21:0] wire1;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:4.38-4.43" *)
  input [21:0] wire2;
  wire [21:0] wire2;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:3.31-3.36" *)
  input [20:0] wire4;
  wire [20:0] wire4;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:7.24-7.29" *)
  wire [5:0] wire5;
  (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:2.35-2.36" *)
  output [475:0] y;
  wire [475:0] y;
  assign _000_ = ~wire0[3];
  assign _001_ = ~wire0[2];
  assign _002_ = ~wire0[1];
  assign _003_ = ~wire0[4];
  assign _004_ = ~wire0[5];
  assign _005_[0] = wire2[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  wire2[1];
  assign _005_[1] = wire2[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  wire2[3];
  assign _005_[2] = wire2[4] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  wire2[5];
  assign _005_[3] = wire2[6] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  wire2[7];
  assign _005_[4] = wire2[8] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  wire2[9];
  assign _005_[5] = wire2[10] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  wire2[11];
  assign _005_[6] = wire2[12] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  wire2[13];
  assign _005_[7] = wire2[14] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  wire2[15];
  assign _005_[8] = wire2[16] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  wire2[17];
  assign _005_[9] = wire2[18] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  wire2[19];
  assign _005_[10] = wire2[20] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  wire2[21];
  assign _006_[0] = _005_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  _005_[1];
  assign _006_[1] = _005_[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  _005_[3];
  assign _006_[2] = _005_[4] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  _005_[5];
  assign _006_[3] = _005_[6] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  _005_[7];
  assign _006_[4] = _005_[8] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  _005_[9];
  assign _007_[0] = _006_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  _006_[1];
  assign _007_[1] = _006_[2] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  _006_[3];
  assign _007_[2] = _006_[4] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  _005_[10];
  assign _008_ = _007_[0] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  _007_[1];
  assign _014_ = _008_ |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *)  _007_[2];
  assign _010_[0] = _016_[1] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62" *)  _009_[1];
  assign _010_[3] = _009_[6] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62" *)  _009_[7];
  assign _011_[0] = _010_[0] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62" *)  _010_[1];
  assign _011_[1] = _010_[2] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62" *)  _010_[3];
  assign _011_[2] = _010_[4] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62" *)  _009_[10];
  assign _012_ = _011_[0] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62" *)  _011_[1];
  assign _018_ = _012_ &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62" *)  _011_[2];
  assign _025_[0] = _014_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *) wire4[0] : _026_[0];
  assign _025_[1] = _014_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *) wire4[1] : _002_;
  assign _025_[2] = _014_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *) wire4[2] : _001_;
  assign _025_[3] = _014_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *) wire4[3] : _000_;
  assign _025_[4] = _014_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *) wire4[4] : _003_;
  assign _025_[5] = _014_ ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:10.73-11.74" *) wire4[5] : _004_;
  assign y[0] = wire2[15] ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:9.19-11.75" *) wire1[0] : _025_[0];
  assign y[1] = wire2[15] ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:9.19-11.75" *) wire1[1] : _025_[1];
  assign y[2] = wire2[15] ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:9.19-11.75" *) wire1[2] : _025_[2];
  assign y[3] = wire2[15] ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:9.19-11.75" *) wire1[3] : _025_[3];
  assign y[4] = wire2[15] ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:9.19-11.75" *) wire1[4] : _025_[4];
  assign y[5] = wire2[15] ? (* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:9.19-11.75" *) wire1[5] : _025_[5];
  assign _017_ = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62" *) _016_[21];
  assign _013_[0] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62" *) _019_;
  assign _015_[0] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[0];
  assign _015_[1] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[1];
  assign _015_[2] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[2];
  assign _015_[3] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[3];
  assign _015_[4] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[4];
  assign _015_[5] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[5];
  assign _015_[6] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[6];
  assign _015_[7] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[7];
  assign _015_[8] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[8];
  assign _015_[9] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[9];
  assign _015_[10] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[10];
  assign _015_[11] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[11];
  assign _015_[12] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[12];
  assign _015_[13] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[13];
  assign _015_[14] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[14];
  assign _015_[15] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[15];
  assign _015_[16] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[16];
  assign _015_[17] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[17];
  assign _015_[18] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[18];
  assign _015_[19] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[19];
  assign _015_[20] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[20];
  assign _015_[21] = ~(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) wire2[21];
  assign _026_[0] = ~(_013_[0] ^(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.46-11.72" *)  wire0[0]);
  assign _019_ = _017_ |(* src = {0{1'b0}} *)  _018_;
  assign _016_[1] = _015_[1] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _015_[0];
  assign _020_ = wire2[3] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _015_[2];
  assign _021_ = _009_[3] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _015_[5];
  assign _022_ = _010_[1] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _016_[3];
  assign _016_[15] = _011_[1] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _016_[7];
  assign _009_[1] = wire2[3] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  wire2[2];
  assign _009_[2] = wire2[5] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _015_[4];
  assign _009_[3] = wire2[7] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _015_[6];
  assign _009_[4] = _015_[9] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _015_[8];
  assign _009_[5] = _015_[11] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _015_[10];
  assign _009_[6] = _015_[13] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _015_[12];
  assign _009_[7] = _015_[15] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _015_[14];
  assign _009_[8] = _015_[17] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _015_[16];
  assign _009_[9] = _015_[19] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _015_[18];
  assign _009_[10] = _015_[21] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _015_[20];
  assign _010_[1] = _009_[3] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _009_[2];
  assign _010_[2] = _009_[5] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _009_[4];
  assign _010_[4] = _009_[9] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _009_[8];
  assign _016_[19] = _010_[4] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _016_[15];
  assign _016_[21] = _009_[10] &(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _016_[19];
  assign _023_ = _015_[3] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _020_;
  assign _016_[3] = _023_ |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _010_[0];
  assign _024_ = _015_[7] |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _021_;
  assign _016_[7] = _024_ |(* src = "/doc/Verismith/03-06-04/fuzz_888/reduce_yosys.v:11.47-11.62|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _022_;
  assign _009_[0] = _016_[1];
  assign _013_[21:1] = 21'h000000;
  assign _016_[0] = _015_[0];
  assign _025_[22] = 1'h0;
  assign _026_[5:1] = { _004_, _003_, _000_, _001_, _002_ };
  assign wire5 = y[5:0];
  assign y[475:6] = 470'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
endmodule
